### ISSUE TITLE
Add ability to set more report values

### ISSUE THREAD

**Issue by ewels** [MultiQC/MultiQC_Clarity#8]
It'd be nice to be able to set a few more variables in the report from the LIMS. Mainly [these ones](http://multiqc.info/docs/#titles-and-introductory-text):

```yaml
title: "My Title"
subtitle: "A subtitle to go underneath in grey"
intro_text: "MultiQC reports summarise analysis results."
report_comment: "This is a comment about this report."
```
